# Generated by Django 4.2.5 on 2023-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('plate_number', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
    ]
