# Generated by Django 4.2.6 on 2023-10-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeSystemFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_brake', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('parking_brake', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('rotor', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('brake_hose', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('low_pressuree_device', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CouplingDeviceFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('fifth_wheel', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('pintle_hooks', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('drawbar', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EngineOperationFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('fan', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('oil_pressure', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('radiator', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('battery', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExhaustSystemFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_position_exhaust', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('fuel_line_exhaust', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('muffler', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FuelSystemFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('visible_leak', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('fuel_tank_filler_cap', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('fuel_tank', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LightingDevicesFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('head_light', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('brake_light', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('tail_light', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('dash_light', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('clearance_light', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('turn_indicator', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('transmission_fluid', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('clutch', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('heater', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('mirror', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('frame', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('body', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEquipmentFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_belt', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('fire_extinguisher', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('flare', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('decal', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('spare_bulb', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('turn_indicator', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringMechanismFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('steering_wheel', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('steering_column', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('front_axel_beam', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('steering_gear_box', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('pitman_arm', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('power_steering', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('ball_and_socket_joints', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('tie_rods', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('spring_assembly_and_bolts', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('tracking_components', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TiresFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('air_pressure', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('chains', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WheelFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('wheel_and_rims', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('lock_or_side_rings', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('fasteners', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('welds', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WindShieldFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('glass', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
                ('wiper_power_unit', models.CharField(choices=[('OK', 'OK'), ('NEEDS REPAIR', 'Needs Repair'), ('NOT APPLICABLE', 'Not Applicable'), ('REPAIRED', 'Repaired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFault',
            fields=[
                ('fault_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=450)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor'), ('HIGH RISK', 'High Risk')], max_length=25)),
                ('recommendation', models.TextField(max_length=250)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
