# Generated by Django 4.2.5 on 2023-09-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('vehicle', '0002_servicereport_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
