# Generated by Django 4.2.6 on 2023-10-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=40)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('TOWING REQUEST', 'Towing Request'), ('REPAIR RESERVATION', 'Repair Reservation')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_status', models.CharField(max_length=40)),
                ('payment_status', models.CharField(max_length=40)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.billing')),
                ('invoice_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
        ),
    ]
